### ISSUE TITLE
Error relating to __set() inside WP_Error in add() method Wordpress 4.2.1

### ISSUE THREAD

**Issue by sworup** [LucaRosaldi/wpfn-notifications#2]
I've been using this calls for a while and it has worked wonderfully. Thanks for that but since the new version of wordpress I'm getting this issue.

<b>Fatal error</b>
: Call to undefined method WPFN_Notification::__set() in
<b><Plugin_Path>\inc\class.wpfn-notification.php</b>
on line
<b>101</b>

I think the error is because WP_Error class doesn't have setter methods anymore. I'm not sure though.

**Comment by sworup** [comment]
I have commented out the add() method, sending the add call directly to WP_Error which seems to be working with my version for now. 
Temporary fix.

**Comment by jylyn** [comment]
I have the same problem.  Just stumbled on this class and it looked perfect to just include and go with no hassle, hope this can be fixed!

@sworup would you mind sharing your code?  I'm not familiar with WP_Error at all.

**Comment by sworup** [comment]
WP_Error is the class that handles errors exceptions on behalf of Wordpress, it ships with Wordpress. WPFN_Notification inherits from WP_Error so everything WP_Error does would be available to WPFN_Notification including the add method. 
WPFN_Notification however overrides the add method to include custom methods, we're getting our error there. Comment out the add method would send all the calls to add directly to WP_Error. 

Just look for this method in the class and comment it out for now.
```
/*
public function add($code, $message, $data = '') {
    $this->__set( 'errors', array( $code => array( $message ) ) );
    if ( ! empty($data) ) {
      $this->__set( 'error_data', array( $code => array( $data ) ) );
      if ( isset( $data['status'] ) )
        $this->status = $data['status'];
      if ( isset( $data['icon'] ) )
        $this->icon = $data['icon'];
    }
  }
*/
```

> Its a temporary fix though.

**Comment by LucaRosaldi** [comment]
Yup, the WP_Error does not have a __set method anymore. Fixed the issue and updated the repository. @sworup Thanks for the feedback!
